MIN_WEEKLY_SIGNALS = 5
MIN_MONTHLY_WEEKS = 3
EPISODIC_PROMOTION_WEEKS = 3

PERSONAL_MODEL_UPDATE_WEIGHT = 0.1

CONFIDENCE_DECAY = 0.98
VECTOR_DECAY = 0.97
# TODO: reduce STM_TTL_DAYS for production; 1500 is for lab/backfill to keep signals available.
STM_TTL_DAYS = 1500

MIN_VAL = 0.0
MAX_VAL = 1.0
