-- Migration: 0005_email_digests
-- Description: Email Digest table for LLM-powered cognitive offload
-- Date: 2026-02-07
--
-- Stores structured digest output (triage, action items, commitments)
-- generated by running email bodies through an LLM. Bodies are NEVER stored.

-- =============================================================================
-- EMAIL_DIGESTS TABLE
-- =============================================================================

CREATE TABLE IF NOT EXISTS email_digests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    person_id UUID NOT NULL REFERENCES auth_users(id) ON DELETE CASCADE,

    -- Digest metadata
    digest_type TEXT NOT NULL DEFAULT 'daily',  -- 'daily', 'weekly', 'on_demand'
    status TEXT NOT NULL DEFAULT 'pending',       -- 'pending', 'generating', 'complete', 'error'

    -- Time window this digest covers
    period_start TIMESTAMPTZ,
    period_end TIMESTAMPTZ,

    -- Triage summary counts
    triage_counts JSONB DEFAULT '{}',
    -- Expected shape: {"needs_action": 3, "fyi": 8, "noise": 42}

    -- Action items requiring user response
    action_items JSONB DEFAULT '[]',
    -- Expected shape: [{"subject": "...", "sender": "...", "sender_name": "...",
    --   "action_summary": "...", "deadline": "...", "priority": "high|medium|low",
    --   "draft_reply": "...", "message_id": "..."}]

    -- FYI items worth knowing about
    fyi_items JSONB DEFAULT '[]',
    -- Expected shape: [{"subject": "...", "sender": "...", "sender_name": "...",
    --   "one_line_summary": "..."}]

    -- Noise summary (newsletters, automated, marketing)
    noise_summary JSONB DEFAULT '{}',
    -- Expected shape: {"count": 42, "categories": {"newsletters": 15, "marketing": 12, ...}}

    -- Commitments the user made in sent emails
    commitments JSONB DEFAULT '[]',
    -- Expected shape: [{"commitment": "...", "deadline": "...", "subject": "...",
    --   "recipient": "..."}]

    -- Generation metadata
    emails_analyzed INTEGER DEFAULT 0,
    model_used TEXT,
    generation_time_ms INTEGER,
    error_message TEXT,

    -- Timestamps
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_email_digests_person_created
    ON email_digests(person_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_email_digests_person_status
    ON email_digests(person_id, status);

-- Trigger for updated_at (reuse function from 0004)
DROP TRIGGER IF EXISTS trg_email_digests_updated_at ON email_digests;
CREATE TRIGGER trg_email_digests_updated_at
    BEFORE UPDATE ON email_digests
    FOR EACH ROW
    EXECUTE FUNCTION update_email_updated_at();

-- RLS
ALTER TABLE email_digests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS email_digests_user_policy ON email_digests;
CREATE POLICY email_digests_user_policy ON email_digests
    FOR ALL USING (person_id = auth.uid());

-- Comment
COMMENT ON TABLE email_digests IS 'LLM-generated email digests with triage, actions, and commitments. Email bodies are never stored.';
