"""
Factory functions for creating test data.

These factories create properly structured test objects
that can be used in both unit and integration tests.
"""

import uuid
from datetime import datetime, timedelta
from typing import Optional, Dict, Any

from .constants import DEMO_USER_ID, OPERATING_SYSTEM_ADAPTIVE


# ─────────────────────────────────────────────────────────────────────────────
# ID Generators
# ─────────────────────────────────────────────────────────────────────────────

def generate_uuid() -> str:
    """Generate a new UUID string."""
    return str(uuid.uuid4())


def generate_test_person_id(suffix: str = "") -> str:
    """Generate a deterministic test person ID."""
    base = "test-user-"
    if suffix:
        return f"{base}{suffix}"
    return f"{base}{generate_uuid()[:8]}"


# ─────────────────────────────────────────────────────────────────────────────
# User Factories
# ─────────────────────────────────────────────────────────────────────────────

def create_test_user(
    person_id: Optional[str] = None,
    name: str = "Test User",
    email: Optional[str] = None,
    operating_system: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Create a test user data structure.

    Args:
        person_id: Optional user ID (generates one if not provided)
        name: User display name
        email: User email (generates one if not provided)
        operating_system: Friction Framework OS (defaults to Adaptive)

    Returns:
        Dict with user data suitable for database insertion
    """
    pid = person_id or generate_uuid()
    return {
        "person_id": pid,
        "name": name,
        "email": email or f"{name.lower().replace(' ', '.')}@test.sakhi.ai",
        "operating_system": operating_system or OPERATING_SYSTEM_ADAPTIVE,
        "created_at": datetime.now(),
    }


# ─────────────────────────────────────────────────────────────────────────────
# Journal Entry Factories
# ─────────────────────────────────────────────────────────────────────────────

def create_test_journal_entry(
    person_id: str = DEMO_USER_ID,
    title: str = "Test Entry",
    content: str = "This is a test journal entry.",
    mood: str = "neutral",
    created_at: Optional[datetime] = None,
) -> Dict[str, Any]:
    """
    Create a test journal entry data structure.

    Args:
        person_id: User ID
        title: Entry title
        content: Entry content
        mood: Mood tag
        created_at: Creation timestamp (defaults to now)

    Returns:
        Dict with journal entry data
    """
    return {
        "id": generate_uuid(),
        "user_id": person_id,
        "title": title,
        "content": content,
        "mood": mood,
        "facets": {},
        "created_at": created_at or datetime.now(),
    }


def create_test_journal_entries_batch(
    person_id: str = DEMO_USER_ID,
    count: int = 5,
    days_back: int = 7,
) -> list[Dict[str, Any]]:
    """
    Create a batch of test journal entries spread over time.

    Args:
        person_id: User ID
        count: Number of entries to create
        days_back: Spread entries over this many days

    Returns:
        List of journal entry dicts
    """
    entries = []
    moods = ["positive", "neutral", "anxious", "calm", "energized"]

    for i in range(count):
        days_offset = (days_back * i) // count
        created_at = datetime.now() - timedelta(days=days_offset)
        entries.append(
            create_test_journal_entry(
                person_id=person_id,
                title=f"Entry {i + 1}",
                content=f"Journal content for entry {i + 1}. Reflecting on the day.",
                mood=moods[i % len(moods)],
                created_at=created_at,
            )
        )

    return entries


# ─────────────────────────────────────────────────────────────────────────────
# Memory Factories
# ─────────────────────────────────────────────────────────────────────────────

def create_test_memory_short_term(
    person_id: str = DEMO_USER_ID,
    content: str = "Test memory content",
    source: str = "conversation",
) -> Dict[str, Any]:
    """
    Create a test short-term memory record.

    Args:
        person_id: User ID
        content: Memory content
        source: Source of memory (conversation, journal, etc.)

    Returns:
        Dict with STM data
    """
    return {
        "id": generate_uuid(),
        "person_id": person_id,
        "content": content,
        "source": source,
        "created_at": datetime.now(),
        # Note: embedding would be generated by the embeddings service
    }


def create_test_memory_episodic(
    person_id: str = DEMO_USER_ID,
    summary: str = "Daily episode summary",
    date: Optional[datetime] = None,
) -> Dict[str, Any]:
    """
    Create a test episodic memory record.

    Args:
        person_id: User ID
        summary: Episode summary
        date: Episode date (defaults to today)

    Returns:
        Dict with episodic memory data
    """
    episode_date = date or datetime.now()
    return {
        "id": generate_uuid(),
        "person_id": person_id,
        "content": summary,
        "content_hash": f"hash_{generate_uuid()[:8]}",
        "created_at": episode_date,
    }


# ─────────────────────────────────────────────────────────────────────────────
# Conversation Factories
# ─────────────────────────────────────────────────────────────────────────────

def create_test_turn_request(
    person_id: str = DEMO_USER_ID,
    message: str = "Hello, how are you?",
    thread_id: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Create a test conversation turn request.

    Args:
        person_id: User ID
        message: User message
        thread_id: Conversation thread ID

    Returns:
        Dict suitable for POST to /v2/turn
    """
    return {
        "person_id": person_id,
        "message": message,
        "thread_id": thread_id or generate_uuid(),
    }


def create_test_conversation_thread(
    person_id: str = DEMO_USER_ID,
    messages: Optional[list[str]] = None,
) -> list[Dict[str, Any]]:
    """
    Create a test conversation thread with multiple turns.

    Args:
        person_id: User ID
        messages: List of user messages (generates defaults if not provided)

    Returns:
        List of turn request dicts with same thread_id
    """
    thread_id = generate_uuid()
    msgs = messages or [
        "Hi there!",
        "I've been feeling stressed lately.",
        "What do you suggest I do?",
    ]

    return [
        create_test_turn_request(
            person_id=person_id,
            message=msg,
            thread_id=thread_id,
        )
        for msg in msgs
    ]


# ─────────────────────────────────────────────────────────────────────────────
# Intervention Factories
# ─────────────────────────────────────────────────────────────────────────────

def create_test_intervention_plan(
    person_id: str = DEMO_USER_ID,
    intervention_type: str = "activity",
    intervention_name: str = "Morning walk",
    target_symptom: str = "stress",
    duration_days: int = 14,
) -> Dict[str, Any]:
    """
    Create a test intervention plan.

    Args:
        person_id: User ID
        intervention_type: Type (activity, food, mindfulness, etc.)
        intervention_name: Display name
        target_symptom: What this intervention addresses
        duration_days: Plan duration

    Returns:
        Dict with intervention plan data
    """
    start_date = datetime.now().date()
    return {
        "id": generate_uuid(),
        "person_id": person_id,
        "intervention_type": intervention_type,
        "intervention_name": intervention_name,
        "schedule_type": "daily",
        "schedule_days": None,
        "target_per_day": 1,
        "start_date": start_date,
        "end_date": start_date + timedelta(days=duration_days),
        "target_symptom": target_symptom,
        "target_dosha": "vata",
        "status": "active",
        "total_scheduled": duration_days,
        "total_completed": 0,
        "current_streak": 0,
        "longest_streak": 0,
        "created_at": datetime.now(),
    }


# ─────────────────────────────────────────────────────────────────────────────
# Personal Model Factories
# ─────────────────────────────────────────────────────────────────────────────

def create_test_personal_model(
    person_id: str = DEMO_USER_ID,
    operating_system: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    """
    Create a test personal model structure.

    Args:
        person_id: User ID
        operating_system: Friction Framework OS config

    Returns:
        Dict with personal model data
    """
    return {
        "person_id": person_id,
        "operating_system": operating_system or OPERATING_SYSTEM_ADAPTIVE,
        "life_context": {
            "age_range": "30-40",
            "life_phase": "career-building",
            "roles": ["professional", "parent"],
        },
        "decision_profile": {
            "risk_tolerance": 0.5,
            "time_horizon": "medium",
            "flexibility": 0.7,
        },
        "short_term": {
            "current_dosha_drift": {"vata": 0.1, "pitta": 0.0, "kapha": -0.1},
        },
        "updated_at": datetime.now(),
    }
